# Generated by Django 4.2.6 on 2023-11-27 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol_area_detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Arbol_especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Arbol_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Vereda_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Arbolado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maps_long', models.FloatField()),
                ('maps_lat', models.FloatField()),
                ('observacion', models.TextField(max_length=200)),
                ('fecha_act', models.DateField(auto_now=True)),
                ('altura_calle', models.IntegerField()),
                ('nombre_calle', models.CharField(max_length=50)),
                ('ancho_vereda', models.FloatField()),
                ('altura_aprox', models.IntegerField()),
                ('circurns', models.FloatField()),
                ('diametro', models.FloatField()),
                ('tiene_clavel', models.BooleanField()),
                ('vereda_damaged', models.BooleanField()),
                ('vereda_levantada', models.BooleanField()),
                ('element_rare', models.BooleanField()),
                ('element_rare_type', models.TextField(max_length=50)),
                ('element_rare_desc', models.TextField(max_length=200)),
                ('activo', models.BooleanField()),
                ('arbol_area_detalles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arb_datos.arbol_area_detalles')),
                ('arbol_especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arb_datos.arbol_especie')),
                ('arbol_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arb_datos.arbol_estado')),
                ('vereda_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arb_datos.vereda_estado')),
            ],
        ),
    ]
