# Generated by Django 4.2.6 on 2023-11-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arb_datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbolado',
            name='element_rare_desc',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='arbolado',
            name='element_rare_type',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
