# Generated by Django 4.2.6 on 2023-11-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arb_datos', '0002_alter_arbolado_element_rare_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbolado',
            name='element_rare_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='arbolado',
            name='element_rare_type',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
